//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dvhd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSo
    {
        public int id { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string quoctich { get; set; }
        public string hokhauthuongtru { get; set; }
        public string choohientai { get; set; }
        public string hotencha { get; set; }
        public string hotenme { get; set; }
        public string cmthochieu { get; set; }
        public string noicap { get; set; }
        public Nullable<System.DateTime> ngaycap { get; set; }
        public string coquancap { get; set; }
        public string noicongtac { get; set; }
        public string diachicoquan { get; set; }
        public string anhdoituong { get; set; }
        public string dacdiemnhandang { get; set; }
        public string tienantiensu { get; set; }
        public Nullable<System.DateTime> thoigianvipham { get; set; }
        public string quanvipham { get; set; }
        public string tinhvipham { get; set; }
        public string motavipham { get; set; }
        public string hinhthucvipham { get; set; }
        public string hanhvivipham { get; set; }
        public string phuongthucvanchuyen { get; set; }
        public string tuyenduongvanchuyen { get; set; }
        public string loaidongvat { get; set; }
        public string tinhtrangsong { get; set; }
        public string donvitinh { get; set; }
        public string soluongchitiet { get; set; }
        public string trigiatangvat { get; set; }
        public string tinhtrangbaoton { get; set; }
        public string anhdongvat { get; set; }
        public string donvibatgiu { get; set; }
        public string tendonvibatgiu { get; set; }
        public Nullable<System.DateTime> thoigianxuly { get; set; }
        public string ketquaxuly { get; set; }
        public string donvixuly { get; set; }
        public string tendonvixuly { get; set; }
        public string hotencanboxuly { get; set; }
        public string capbac { get; set; }
        public string diachilienhe { get; set; }
        public Nullable<System.DateTime> ngayxuly { get; set; }
        public string bican { get; set; }
        public string ketquaxulychitiet { get; set; }
        public string motachitietxuly { get; set; }
        public string hosocode { get; set; }
    }
}
